asf_scheduler_homepage:
    path: /admin/scheduler
    defaults: { _controller: "ASFSchedulerBundle:Default:index" }
    
asf_scheduler_calendar_event:
    resource: "@ASFSchedulerBundle/Resources/config/routing/calendar_event.yml"
    prefix: /admin/scheduler
    
asf_scheduler_calendar_event_category:
    resource: "@ASFSchedulerBundle/Resources/config/routing/calendar_event_category.yml"
    prefix: /admin/scheduler
    
asf_scheduler_fullcalendar_loader:
    path: /admin/scheduler/load-calendar-events
    defaults: { _controller: "ASFSchedulerBundle:AjaxRequest:loadCalendar" }
    options:
        expose: true